# Auto-generated by generate-random-rpms.sh — do not edit manually
Name:           random-bronze-mighty-raven
Version:        3.1.3
Release:        1%{?dist}
Summary:        The Bronze Mighty Raven - A randomly generated test package

License:        MIT
URL:            https://github.com/example/random-rpms
BuildArch:      noarch

%description
Meet the Bronze Mighty Raven!
A whimsical test package generated for RPM repository testing.
Package: random-bronze-mighty-raven v3.1.3

%install
mkdir -p %{buildroot}%{_bindir}

cat > %{buildroot}%{_bindir}/random-bronze-mighty-raven << 'SCRIPT'
#!/bin/bash
# random-bronze-mighty-raven v3.1.3
# Auto-generated test package

VERSION="3.1.3"
DISPLAY_NAME="Bronze Mighty Raven"
PKG_NAME="random-bronze-mighty-raven"

show_art() {
    echo ""
    echo "  Bronze Mighty Raven"
    echo "  v3.1.3"
    echo ""
    cat << 'ART'
      ___
     (o o)
    (  V  )
   /--m-m--\
ART
    echo ""
    echo "  Installed from: Azure Blob Storage RPM Repository"
    echo ""
}

case "$1" in
    --version|-v)
        echo "${PKG_NAME} v${VERSION}"
        ;;
    --info|-i)
        echo "Package:   ${PKG_NAME}"
        echo "Version:   ${VERSION}"
        echo "Name:      ${DISPLAY_NAME}"
        echo "Type:      Random test package"
        echo "Source:    Azure Blob Storage"
        echo "Hostname:  $(hostname)"
        echo "OS:        $(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"')"
        echo "Date:      $(date)"
        ;;
    --help|-h)
        echo "Usage: ${PKG_NAME} [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  --version, -v    Show version"
        echo "  --info,    -i    Show detailed info"
        echo "  --help,    -h    Show this help"
        echo ""
        echo "With no options, displays ASCII art."
        ;;
    *)
        show_art
        ;;
esac
SCRIPT

chmod +x %{buildroot}%{_bindir}/random-bronze-mighty-raven

%files
%{_bindir}/random-bronze-mighty-raven

%changelog
* Mon Feb 09 2026 Random Generator <random@example.com> - 3.1.3-1
- Auto-generated random test package: Bronze Mighty Raven
