# Auto-generated by generate-random-rpms.sh — do not edit manually
Name:           random-emerald-super-cobra
Version:        6.0.5
Release:        1%{?dist}
Summary:        The Emerald Super Cobra - A randomly generated test package

License:        MIT
URL:            https://github.com/example/random-rpms
BuildArch:      noarch

%description
Meet the Emerald Super Cobra!
A whimsical test package generated for RPM repository testing.
Package: random-emerald-super-cobra v6.0.5

%install
mkdir -p %{buildroot}%{_bindir}

cat > %{buildroot}%{_bindir}/random-emerald-super-cobra << 'SCRIPT'
#!/bin/bash
# random-emerald-super-cobra v6.0.5
# Auto-generated test package

VERSION="6.0.5"
DISPLAY_NAME="Emerald Super Cobra"
PKG_NAME="random-emerald-super-cobra"

show_art() {
    echo ""
    echo "  Emerald Super Cobra"
    echo "  v6.0.5"
    echo ""
    cat << 'ART'
   +--------+
   | ^    ^ |
   |   <>   |
   |  \__/  |
   +--------+
ART
    echo ""
    echo "  Installed from: Azure Blob Storage RPM Repository"
    echo ""
}

case "$1" in
    --version|-v)
        echo "${PKG_NAME} v${VERSION}"
        ;;
    --info|-i)
        echo "Package:   ${PKG_NAME}"
        echo "Version:   ${VERSION}"
        echo "Name:      ${DISPLAY_NAME}"
        echo "Type:      Random test package"
        echo "Source:    Azure Blob Storage"
        echo "Hostname:  $(hostname)"
        echo "OS:        $(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"')"
        echo "Date:      $(date)"
        ;;
    --help|-h)
        echo "Usage: ${PKG_NAME} [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  --version, -v    Show version"
        echo "  --info,    -i    Show detailed info"
        echo "  --help,    -h    Show this help"
        echo ""
        echo "With no options, displays ASCII art."
        ;;
    *)
        show_art
        ;;
esac
SCRIPT

chmod +x %{buildroot}%{_bindir}/random-emerald-super-cobra

%files
%{_bindir}/random-emerald-super-cobra

%changelog
* Mon Feb 09 2026 Random Generator <random@example.com> - 6.0.5-1
- Auto-generated random test package: Emerald Super Cobra
